filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/suricata/eve.json

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "suricata"

setup.ilm.enabled: false
setup.template.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "suricata-%%{+yyyy.MM.dd}"
