%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[127.0.0.1/32, ::1/128]"
    EXTERNAL_NET: "any"
    HTTP_SERVERS: "$HOME_NET"
  port-groups:
    HTTP_PORTS: "[8000]"

default-rule-path: /etc/suricata/rules
rule-files:
  - suricata.rules

af-packet:
  - interface: lo
    host-mode: yes
    use-mmap: yes
    tpacket-v3: yes
    checksum-checks: no

nfq:
  interface: lo
  mode: accept
  fail-open: no
  threads: no
  checksum-checks: no
  defrag: yes

app-layer:
  protocols:
    http:
      enabled: yes
      detection-only: no
      ports: "$HTTP_PORTS"

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert:
            payload: yes
            payload-printable: yes
        - http:
            extended: yes
            include-body-for: ["application/json"]
        - drop:
            payload: yes
            payload-printable: yes

logging:
  default-log-level: info
  outputs:
    - console:
        enabled: yes
