version: '3.8'

services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    volumes:
      - ./suricata/logs:/var/log/suricata
      - ./suricata/config:/etc/suricata
      - ./suricata/rules:/etc/suricata/rules
    command:
      - -q
      - "0"
#      - -i
#      - lo
      - -c
      - /etc/suricata/suricata.yaml
      - -l
      - /var/log/suricata

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:8.7.0
    container_name: packetbeat
    network_mode: host
    extra_hosts:
      - "elasticsearch:127.0.0.1"
    depends_on:
      - elasticsearch
      - kibana
    cap_add:
      - NET_ADMIN
      - NET_RAW
    user: root
    volumes:
      - ./packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.0
    container_name: filebeat
    depends_on:
      - elasticsearch
      - kibana
    user: root
    volumes:
      - ./suricata/logs:/var/log/suricata
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: [
      "filebeat", "-e",
      "--strict.perms=false",
      "-E", "output.elasticsearch.hosts=['elasticsearch:9200']"
    ]

volumes:
  elastic_data:
